import pretty_midi

pitch = ['C_major', 'C_minor', 'D_major', 'D_minor', 'E_major', 'E_minor',
                          'F_major', 'F_minor', 'G_major', 'G_minor', 'A_major', 'A_minor',
                          'B_major', 'B_minor', 'Db_major', 'Db_minor', 'Eb_major', 'Eb_minor',
                          'Gb_major', 'Gb_minor', 'Ab_major', 'Ab_minor', 'A_phrygian_major', 'A_phrygian_minor',
                          'Ab_phrygian_major', 'Ab_phyrgian_minor', 'B_phrygian_major', 'B_phrygian_minor',
                          'Bb_phrygian_major', 'Bb_phyrgian_minor', 'C_phrygian_major', 'C_phrygian_minor',
                          'Db_phrygian_major', 'Db_phrygian_minor', 'D_phrygian_major', 'D_phrygian_minor',
                          'E_phrygian_major', 'E_phrygian_minor', 'F_phrygian_major', 'F_phrygian_minor',
                          'Eb_phrygian_major', 'Eb_phrygian_minor', 'Gb_phrygian_major', 'Gb_phrygian_minor',
                          'G_phrygian_major', 'G_phrygian_minor', 'A_phrygian_major', 'A_phrygian_minor',
                          'Ab_dorian_major', 'Ab_dorian_minor', 'B_dorian_major', 'B_dorian_minor', 'Bb_dorian_major',
                          'Bb_dorian_minor', 'C_dorian_major', 'C_dorian_minor', 'Db_dorian_major', 'Db_dorian_minor', 'D_dorian_major',
                          'D_dorian_minor', 'E_dorian_major', 'E_dorian_minor', 'F_dorian_major', 'F_dorian_minor', 'Eb_dorian_major',
                          'Eb_dorian_minor', 'Gb_dorian_major', 'Gb_dorian_minor', 'G_dorian_major', 'G_dorian_minor', 'A_dorian_major',
                          'A_dorian_minor', 'Ab_dorian_major', 'Ab_dorian_minor', 'B_dorian_major', 'B_dorian_minor', 'Bb_dorian_major',
                          'Bb_dorian_minor', 'C_dorian_major', 'C_dorian_minor', 'Db_dorian_major', 'Db_dorian_minor', 'D_dorian_major',
                          'D_dorian_minor', 'E_dorian_major', 'E_dorian_minor', 'F_dorian_major', 'F_dorian_minor', 'Eb_dorian_major',
                          'A_lydian_major', 'A_lydian_minor', 'Ab_lydian_major', 'Ab_lydian_minor', 'B_lydian_major', 'B_lydian_minor',
                          'Bb_lydian_major', 'Bb_lydian_minor', 'C_lydian_major', 'C_lydian_minor', 'Db_lydian_major', 'Db_lydian_minor',
                          'D_lydian_major', 'D_lydian_minor', 'E_lydian_major', 'E_lydian_minor', 'F_lydian_major', 'F_lydian_minor',
                          'Eb_lydian_major', 'Eb_lydian_minor', 'Gb_lydian_major', 'Gb_lydian_minor', 'G_lydian_major', 'G_lydian_minor',
                          'Ab_mixolydian_major', 'Ab_mixolydian_minor', 'A_mixolydian_major', 'A_mixolydian_minor', 'Bb_mixolydian_major',
                          'Bb_mixolydian_minor', 'B_mixolydian_major', 'B_mixolydian_minor', 'C_mixolydian_major', 'C_mixolydian_minor',
                          'Db_mixolydian_major', 'Db_mixolydian_minor', 'D_mixolydian_major', 'D_mixolydian_minor', 'E_mixolydian_major',
                          'E_mixolydian_minor', 'F_mixolydian_major', 'F_mixolydian_minor', 'Gb_mixolydian_major', 'Gb_mixolydian_minor',
                          'G_mixolydian_major', 'G_mixolydian_minor', 'A_ionian_major', 'A_ionian_minor', 'Ab_ionian_major', 'Ab_ionian_minor',
                          'Bb_ionian_major', 'Bb_ionian_minor', 'B_ionian_major', 'B_ionian_minor', 'C_ionian_major', 'C_ionian_minor',
                          'Db_ionian_major', 'Db_ionian_minor', 'D_ionian_major', 'D_ionian_minor', 'E_ionian_major', 'E_ionian_minor',
                          'F_ionian_major', 'F_ionian_minor', 'G_ionian_major', 'G_ionian_minor', 'Gb_ionian_major', 'Gb_ionian_minor',
                          'Eb_dorian_major', 'Eb_dorian_minor', 'Gb_dorian_major', 'Gb_dorian_minor', 'G_dorian_major', 'G_dorian_minor',]
